---
tags: NumPy, triage
---

# 2021-08-11 NumPy Development Meeting -- Triage

Note: we alternate between [community meetings](https://hackmd.io/76o-IxCjQX2mOXO_wwkcpg) and triage meetings.

- Time: 9am Pacific Time
- Join via Zoom at https://berkeley.zoom.us/j/762261535 (or [dial-in](https://berkeley.zoom.us/u/aC3ENhycM))
- [Trello workboard](https://trello.com/b/Azg4fYZH/numpy-at-bids)
- [Previous community meetings](https://github.com/numpy/archive/tree/master/status_meetings)
- [Previous triage meetings](https://github.com/numpy/archive/tree/master/triage_meetings)


**Present:** Chuck, Sebastian, Ross, Matti


## Triage

* [PRs and issues labelled with "Triage-Review"](https://github.com/numpy/numpy/labels/Triage-review) (please add)

* [PRs and issues labeled with "needs decision"](https://github.com/numpy/numpy/labels/54%20-%20Needs%20decision) (50 open)

* [Open PRs (>250 open)](https://github.com/numpy/numpy/pulls) can we get this below 200?

* Ross' list of cross-referenced issues: https://rossbar.github.io/github_graphql/index.html


## Followup



## Topics

* 3.10 dev-wheels :tada:

* Worse tracebacks on Python 3.7? (I think the following is the main change)
  * The changes seem OK, and chances are we will drop 3.7 anyway.  (keep try-except for now, maybe we can delete it)
  * Other 3.7 issues: array-api, typing? 

  <details>
  
  ```python
  In [7]: np.concatenate(([1], [[2, 3]]), asdf=12)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-7-74cce4c6add4> in <module>
    ----> 1 np.concatenate(([1], [[2, 3]]), asdf=12)

    ~/forks/numpy/build/testenv/lib/python3.9/site-packages/numpy/core/overrides.py in concatenate(*args, **kwargs)

    TypeError: concatenate() got an unexpected keyword argument 'asdf'

    In [8]: np.concatenate(([1], [[2, 3]]))
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-8-bd4a85822cd5> in <module>
    ----> 1 np.concatenate(([1], [[2, 3]]))

    ~/forks/numpy/build/testenv/lib/python3.9/site-packages/numpy/core/overrides.py in concatenate(*args, **kwargs)

    ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
  ```
  vs. the worse version adding the "public_api":
  ```python
  In [1]: np.concatenate(([1], [[2, 3]]), asdf=12)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-1-74cce4c6add4> in <module>
    ----> 1 np.concatenate(([1], [[2, 3]]), asdf=12)

    ~/forks/numpy/build/testenv/lib/python3.9/site-packages/numpy/core/overrides.py in public_api(*args, **kwargs)
        178         @functools.wraps(implementation)
        179         def public_api(*args, **kwargs):
    --> 180             relevant_args = dispatcher(*args, **kwargs)
        181             return implement_array_function(
        182                 implementation, public_api, relevant_args, args, kwargs)

    TypeError: concatenate() got an unexpected keyword argument 'asdf'

    In [2]: np.concatenate(([1], [[2, 3]]))
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-2-bd4a85822cd5> in <module>
    ----> 1 np.concatenate(([1], [[2, 3]]))

    ~/forks/numpy/build/testenv/lib/python3.9/site-packages/numpy/core/overrides.py in public_api(*args, **kwargs)
        179         def public_api(*args, **kwargs):
        180             relevant_args = dispatcher(*args, **kwargs)
    --> 181             return implement_array_function(
        182                 implementation, public_api, relevant_args, args, kwargs)
        183 

    ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
  ```
  
  </details>

 * Revisit a PR that we've triaged before: https://github.com/numpy/numpy/pull/16221
   - See if there's a straightforward way to handle the compressed formats in the Python std lib

- PyPy 3.8 done in about a month.

* Allocator work is shaping up, still small failures, and context variable is problematic on PyPy (now fixed, but we may want some backcompat hack. If we drop 3.7 then no backcompat needed)

- 32bit releases, do we actually need the wheels?
  - Discussion started, due to old Ubuntu images not existing with 32bit. (also Fedora)
  - Do they still ship 32bit Python packages for the 64 bit distros?
  - conda-forge doesn't have 32bit windows anymore?
    - Anaconda still has 32bit windows but not 32bit linux!  
  - Mail to the list, (a [SPEC](https://scientific-python.org/specs/) may make sense as a policy)?  (It is also easy to put it back if we remove it)
  - Aim for dropping linux 32bit, but probably not windows.

* We need to create a repo for rhaguveer/intel SVML:
  * `intel_svml`?   `svml_vendored`?


* Admin discussions:
  * Mail the mailing list?
  * We should add more people 



---

Please remember to archive this file and commit it to github.com/numpy/archive
